### PR TITLE
Fix the type displayed instead of migration name with migrate-list

### PR DESCRIPTION
**Pull request by samirsilwal**
## Changes
image

- The result of running the migration list returns data as above now. Previously, it used to be just the array of names
- I am not sure about the cause, but don't see any related changes in recent commits

## After fix

image

Fixes https://github.com/leapfrogtechnology/sync-db/issues/204

### CODE REVIEW

**Comment by mesaugat** [comment]
@samirsilwal If this works, we can change the base branch to `fix/remove-error-log-when-dir-does-not-exist`. Trying to make a 2.0.1 release there.

**Comment by samirsilwal** [comment]
> @samirsilwal If this works, we can change the base branch to `fix/remove-error-log-when-dir-does-not-exist`. Trying to make a 2.0.1 release there.

Yeah it works, i will finalize the PR

**Review by mesaugat — APPROVED** [review]
Looks good to me.

**Comment by mesaugat** [comment]
@samirsilwal Should we do the same for remaining migration list?

**Comment by samirsilwal** [comment]
> @samirsilwal Should we do the same for remaining migration list?

The remaining are array of string so it works with current code

**Pull request merged**
